### ISSUE TITLE
Missing request module 

### ISSUE THREAD

**Issue by Jozefiel** [hellofresh/action-changed-files#37]
Hi.
I'm trying to execute sample workflow via Act, but getting error about missing request module.

```yaml
name: Sample workflow

on:
  pull_request:
    branches:
      - master

jobs:
  generate-matrix:
    name: Generate job matrices
    runs-on: ubuntu-latest
    outputs:
      matrix-python-lib: ${{ steps.neo-python.outputs.matrix }}
    steps:
      - name: Generate matrix | Infrastructure
        id: neo-python
        uses: hellofresh/action-changed-files@v3
        with:
            pattern: ^\w+/python/(?P<environment>[^/]+)
            default-patterns: |
                schellar/python
```

[Sample workflow/Generate job matrices]   🐳  docker exec cmd=[bash --noprofile --norc -e -o pipefail /var/run/act/workflow/neo-python-composite-neo.sh] user= workdir=
| Traceback (most recent call last):
|   File "/var/run/act/actions/hellofresh-action-changed-files@v3/neo/neo.py", line 8, in <module>
|     import requests
| ModuleNotFoundError: No module named 'requests'
